name: Build, Test, and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with OpenCover coverage
        run: |
          dotnet test --no-build --configuration Release \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          /p:CoverletOutput=./TestResults/coverage.opencover.xml \
          --results-directory ./TestResults
      
      - name: Generate OpenCover report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          ~/.dotnet/tools/reportgenerator \
            -reports:TestResults/coverage.opencover.xml \
            -targetdir:TestResults/CoverageReport \
            -reporttypes:OpenCover

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=agiles-2024
            -Dsonar.organization=agiles-2024
            -Dsonar.cs.opencover.reportsPaths=TestResults/CoverageReport/coverage.opencover.xml
            -Dsonar.verbose=true