name: Build, Test, and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Install Packages
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.2.0
          dotnet tool update dotnet-reportgenerator-globaltool -g --version 4.8.7

      - name: Build solution
        run: |
          dotnet build --configuration Release -p:DeterministicSourcePaths=true

      - name: Run tests with OpenCover
        run: |
          dotnet test --no-build
          /p:CollectCoverage=true \
          
      - name: Generate SonarQube-compatible Coverage Report
        run: |
          reportgenerator -reports:**/TestResults/**/coverage.opencover.xml -targetdir:sonarqubecoverage -reporttypes:SonarQube
          
      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: | 
            -Dsonar.projectKey=agiles-2024
            -Dsonar.organization=agiles-2024
            -Dsonar.coverageReportPaths=".\sonarqubecoverage\SonarQube.xml"
            -Dsonar.verbose=true