name: Build, Test, and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: |
          dotnet build /home/runner/work/ahorcado/ahorcado/AhocadoTest/AhocadoTest.csproj
          dotnet build /home/runner/work/ahorcado/ahorcado/AhorcadoUiTest/AhorcadoUiTest.csproj

      - name: Run tests for AhocadoTest with OpenCover
        run: dotnet test /home/runner/work/ahorcado/ahorcado/AhocadoTest/bin/Debug/net8.0/AhocadoTest.dll --no-build --collect:"XPlat Code Coverage;Format=opencover"

      - name: Run tests for AhorcadoUiTest with OpenCover
        run: dotnet test /home/runner/work/ahorcado/ahorcado/AhorcadoUiTest/bin/Debug/net8.0/AhorcadoUiTest.dll --no-build --collect:"XPlat Code Coverage;Format=opencover"

      - name: Generate SonarQube-compatible Coverage Report
        run: |
          reportgenerator -reports:**/TestResults/**/coverage.cobertura.xml -targetdir:sonarqubecoverage -reporttypes:SonarQube

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=agiles-2024
            -Dsonar.organization=agiles-2024
            -Dsonar.cs.vscoveragexml.reportsPaths=sonarqubecoverage/SonarQube.xml
            -Dsonar.cs.dotcover.reportsPaths=sonarqubecoverage/SonarQube.xml
            -Dsonar.cs.opencover.reportsPaths=sonarqubecoverage/SonarQube.xml
            -Dsonar.verbose=true