name: Coverage Report

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Run tests with coverage
        run: |
          dotnet test --no-build --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults

      - name: Generate coverage report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          ~/.dotnet/tools/reportgenerator \
            -reports:**/coverage.cobertura.xml \
            -targetdir:TestResults/CoverageReport \
            -reporttypes:Html
