name: SonarCloud Analysis

on:
  workflow_run:
    workflows: ["Build, Test, and Coverage"]
    types:
      - completed

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Download code coverage report
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: ./TestResults/CoverageReport 

      # List files in the coverage report directory for debugging
      - name: List files in the coverage report directory (debugging)
        run: ls -R ./TestResults/CoverageReport # Check if Cobertura.xml exists


      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.X'

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"agiles-2024" /o:"agiles-2024" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="TestResults/CoverageReport/"

          dotnet build --no-restore

          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
